# Generated by Django 4.2.2 on 2023-07-05 08:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import mainsite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(default='Unknown', editable=False, max_length=20)),
                ('vatNumber', models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('passwd', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('wallet', models.PositiveBigIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startPlace', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('endPlace', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('routeLength', models.FloatField(editable=False)),
                ('point', models.PositiveIntegerField(editable=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('start', models.CharField(editable=False, max_length=200, null=True)),
                ('end', models.CharField(editable=False, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='product_photo')),
                ('carbonEmission', models.FloatField(default=0.0, editable=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mainsite.company')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('material', django_enumfield.db.fields.EnumField(default=1, enum=mainsite.models.materials)),
                ('weight', models.FloatField(default=0.0)),
                ('carbonEmission', models.FloatField(default=0.0, editable=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='mainsite.product')),
            ],
        ),
    ]
