# Generated by Django 4.2.2 on 2023-07-22 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_alter_logtprofile_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
