# Generated by Django 4.2.2 on 2023-07-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('product', 'material')},
        ),
    ]
