# Generated by Django 4.2.2 on 2023-07-22 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_abstractlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logtprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='logtprofile',
            name='log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainsite.logt'),
        ),
    ]
