# Generated by Django 4.2.2 on 2023-07-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_component_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('CName', 'EName')},
        ),
    ]
