# Generated by Django 4.2.2 on 2023-07-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_remove_logtprofile_id_alter_logtprofile_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logiprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='logiprofile',
            name='log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainsite.logi'),
        ),
    ]
