# Generated by Django 4.2.2 on 2023-07-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_company_last_login_productlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLog',
        ),
    ]
